Repository inwords/InWords, pull requests merged in 2020-05, with the labels that each got.

#214 gradle app signing
  Android/.gitignore
  Android/android-subproject.gradle
  Android/app/build.gradle
  Android/app/keystore-dummy.properties
  Android/azure-pipelines.yml
  Android/build.gradle
  Android/flipview/build.gradle
  Android/jacoco-configure.gradle
  Android/jacoco-subproject.gradle
  Android/jacoco.gradle
Labels: enhancement

#222 Update azure-pipelines.yml for Azure Pipelines
  Android/azure-pipelines.yml
Labels: enhancement

#229 v1.11-android-build17 fix ndk
  Android/android-subproject.gradle
  Android/azure-pipelines.yml
Labels: enhancement

#231 Server fix: Bug when returns the levels of all users
  WebApi/InWords.WebApi/InWords.WebApi/Modules/ClassicCardGame/EstimateClassicCardGame.cs
Labels: bugfix

#240 Server hotfix: Anonymous access
  WebApi/InWords.WebApi/InWords.WebApi/Controllers/v2/AuthController.cs
  WebApi/InWords.WebApi/InWords.WebApi/Controllers/v2/ProfileController.cs
  WebApi/InWords.WebApi/InWords.WebApi/Controllers/v2/WordSetController.cs
  WebApi/InWords.WebApi/InWords.WebApi/Extensions/AnonimouseHandlerExtention.cs
  WebApi/InWords.WebApi/InWords.WebApi/Extensions/AuthorizeHandlerExtention.cs
  WebApi/InWords.WebApi/InWords.WebApi/Extensions/InWordsDataContextExtentions/InWordsDataContextExtention.cs
  WebApi/InWords.WebApi/InWords.WebApi/Modules/ClassicCardGame/EstimateClassicCardGame.cs
  WebApi/InWords.WebApi/InWords.WebApi/Modules/ClassicCardGame/Extentions/InWordsContextExtention.cs
  WebApi/InWords.WebApi/InWords.WebApi/Modules/ClassicCardGame/SaveLevels.cs
  WebApi/InWords.WebApi/InWords.WebApi/Modules/DictionaryServiceHandler/Words/UpdateWords.cs
  WebApi/InWords.WebApi/InWords.WebApi/Modules/WordsSets/InModuleInitializer.cs
  WebApi/InWords.WebApi/InWords.WebApi/Swagger/Examples/CardGameInfosExample.cs
  WebApi/InWords.WebApi/InWords.WebApi/Swagger/SetVersionInPaths.cs
  WebApi/InWords.WebApi/InWords.WebApi/gRPC/Services/GreeterService.cs
  WebApi/InWords.WebApi/InWords.WebApi/gRPC/Services/WordsSetService.cs
  WebApi/InWords.WebApi/InWords.WebApiTests/Moduls/ClassicCardGame/EstimateClassicCardGameTests.cs
Labels: bugfix

#259 FIX INW-122
  WebApi/InWords.WebApi/InWords.Protobuf/WordSet.v2.proto
  WebApi/InWords.WebApi/InWords.WebApi/Modules/WordsSets/EstimateTraining.cs
  WebApi/InWords.WebApi/InWords.WebApi/Modules/WordsSets/Extentions/SaveHistoryGames.cs
  WebApi/InWords.WebApi/InWords.WebApi/Modules/WordsSets/GameEvaluator/Game/AudioGameLevel.cs
  WebApi/InWords.WebApi/InWords.WebApi/Modules/WordsSets/GameEvaluator/Game/BaseGameLevel.cs
  WebApi/InWords.WebApi/InWords.WebApi/Modules/WordsSets/GameEvaluator/Game/CardGameLevel.cs
  WebApi/InWords.WebApi/InWords.WebApi/Modules/WordsSets/GameEvaluator/Game/IGameLevel.cs
  WebApi/InWords.WebApi/InWords.WebApiTests/Swagger/Examples/ExampleTester.cs
Labels: bugfix

#270 FIX INW-130,131
  WebApi/InWords.WebApi/InWords.Protobuf/WordSet.v2.proto
  WebApi/InWords.WebApi/InWords.WebApi/Modules/DictionaryServiceHandler/Words/AddWords.cs
  WebApi/InWords.WebApi/InWords.WebApi/Modules/DictionaryServiceHandler/Words/UpdateWords.cs
  WebApi/InWords.WebApi/InWords.WebApi/Modules/WordsSets/GetWordSetLevels.cs
Labels: bugfix

#275 INW-133 guest sign in and sign in proposal if not authorised
  Android/app/src/main/java/ru/inwords/inwords/authorisation/data/WebRequestsManagerUnauthorised.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/data/WebRequestsManagerUnauthorisedImpl.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/data/grpc/AuthenticatorGrpcService.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/di/AuthorisationDaggerModule.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/domain/interactor/AuthorisationInteractor.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/domain/interactor/AuthorisationWebInteractor.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/presentation/AuthorisationViewModelFactory.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/presentation/choose_method/ChooseSignMethodFragment.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/presentation/choose_method/ChooseSignMethodViewModel.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/presentation/login/LoginFragment.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/presentation/login/LoginViewModel.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/presentation/registration/RegistrationFragment.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/presentation/registration/RegistrationViewModel.kt
  Android/app/src/main/java/ru/inwords/inwords/game/presentation/OctoGameViewModelFactory.kt
  Android/app/src/main/java/ru/inwords/inwords/game/presentation/games/ContinueGameReducer.kt
  Android/app/src/main/java/ru/inwords/inwords/game/presentation/games/GamesFragment.kt
  Android/app/src/main/java/ru/inwords/inwords/game/presentation/games/GamesViewModel.kt
  Android/app/src/main/java/ru/inwords/inwords/game/presentation/games/recycler/ContinueGameItem.kt
  Android/app/src/main/java/ru/inwords/inwords/main_activity/presentation/MainActivity.kt
  Android/app/src/main/java/ru/inwords/inwords/policy/presentation/PolicyFragment.kt
  Android/app/src/main/java/ru/inwords/inwords/policy/presentation/PolicyViewModel.kt
  Android/app/src/main/java/ru/inwords/inwords/policy/presentation/ProfileViewModelFactory.kt
  Android/app/src/main/java/ru/inwords/inwords/profile/presentation/view/ProfileViewModel.kt
  Android/app/src/main/res/layout/fragment_choose_sign_method.xml
  Android/app/src/main/res/layout/fragment_custom_game_creator.xml
  Android/app/src/main/res/menu/dictionary_menu_action_mode.xml
  Android/app/src/main/res/navigation/nav_graph.xml
Labels: enhancement

#292 Update azure-pipelines.yml for Azure Pipelines
  Android/azure-pipelines.yml
Labels: enhancement

#293 INW-137 level result can become lower fix, proguard fix, redundant dependency removed
  Android/app/build.gradle
  Android/app/proguard-rules.pro
  Android/app/src/main/java/ru/inwords/inwords/game/data/repository/custom_game/GameUtil.kt
  Android/app/src/main/res/xml/fragment_settings.xml
Labels: bugfix, dependencies

#294 versions update for release v2.0-android-build18
  Android/app/build.gradle
  Android/app/src/main/java/ru/inwords/inwords/main_activity/data/source/database/AppRoomDatabase.java
Labels: enhancement

#316 Release v2.0-android-build20
  Android/app/build.gradle
  Android/app/src/main/java/ru/inwords/inwords/authorisation/data/session/SessionHelper.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/domain/interactor/AuthorisationWebInteractor.kt
  Android/app/src/main/java/ru/inwords/inwords/game/domain/model/CardsData.kt
  Android/app/src/main/java/ru/inwords/inwords/game/domain/model/ListeningData.kt
  Android/app/src/main/java/ru/inwords/inwords/game/domain/model/UsersChoice.kt
  Android/app/src/main/java/ru/inwords/inwords/game/presentation/game_level/GameLevelOrchestrator.kt
  Android/app/src/main/java/ru/inwords/inwords/game/presentation/game_level/GameLevelViewModel.kt
  Android/app/src/main/java/ru/inwords/inwords/game/presentation/game_level/GameScene.kt
  Android/app/src/main/java/ru/inwords/inwords/game/presentation/listening/ListeningDataDiffUtilCallback.kt
  Android/app/src/main/java/ru/inwords/inwords/game/presentation/listening/ListeningFragment.kt
  Android/app/src/main/java/ru/inwords/inwords/game/presentation/listening/ListeningLevelFragment.kt
  Android/app/src/main/java/ru/inwords/inwords/game/presentation/listening/ListeningViewModel.kt
  Android/app/src/main/java/ru/inwords/inwords/main_activity/data/ErrorBodyFormatter.kt
  Android/app/src/main/java/ru/inwords/inwords/translation/domain/model/WordTranslation.kt
  Android/app/src/main/res/navigation/nav_graph.xml
  Android/app/src/test/java/ru/inwords/inwords/game/presentation/game_level/GameLevelOrchestratorTest.kt
  Android/app/src/test/java/ru/inwords/inwords/game/presentation/game_level/GameSceneTest.kt
Labels: bugfix

#320 added release notes file for google play, fixed code coverage exclude rules, fixed word card in dictionary in large size font mode
  Android/app/google-play-release-notes.txt
  Android/app/src/main/res/layout/item_dictionary_translation.xml
  Android/jacoco-subproject.gradle
Labels: bugfix, enhancement

#322 INW-144 add toolbar to SettingsFragment and hide navigation, small fixes
  Android/app/src/main/java/ru/inwords/inwords/main_activity/presentation/MainActivity.kt
  Android/app/src/main/java/ru/inwords/inwords/presentation/view_scenario/FragmentWithViewModelAndNav.kt
  Android/app/src/main/java/ru/inwords/inwords/presentation/view_scenario/SettingsContainerFragment.kt
  Android/app/src/main/java/ru/inwords/inwords/presentation/view_scenario/SettingsFragment.kt
  Android/app/src/main/res/layout/fragment_settings_toolbar.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/main/res/xml/fragment_settings.xml
Labels: bugfix

#330 API Release: 2.0.147
  WebApi/InWords.WebApi.IntegrationTests/InWords.WebApi.Tests/InWords.WebApi.Tests.csproj
Labels: API Release, dependencies

#331 Feature/inw 146
  Android/app/src/main/java/ru/inwords/inwords/authorisation/data/AuthenticationException.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/data/AuthenticatorTokenProvider.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/data/AuthorisationRepository.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/data/AuthorisationRepositoryImpl.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/data/NeverAuthenticatedBeforeException.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/data/grpc/AuthenticatorGrpcService.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/data/session/LastAuthInfoProvider.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/data/session/NativeAuthInfo.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/data/session/NativeTokenHolder.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/data/session/SessionHelper.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/data/session/TokenResponse.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/di/AuthorisationModule.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/domain/interactor/AuthorisationWebInteractor.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/presentation/AuthorisationViewModelFactory.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/presentation/AuthorisationViewState.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/presentation/choose_method/ChooseSignMethodFragment.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/presentation/choose_method/ChooseSignMethodViewModel.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/presentation/login/LoginFragment.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/presentation/login/LoginViewModel.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/presentation/registration/RegistrationFragment.kt
  Android/app/src/main/java/ru/inwords/inwords/authorisation/presentation/registration/RegistrationViewModel.kt
  Android/app/src/main/java/ru/inwords/inwords/core/di/CoreModule.kt
  Android/app/src/main/java/ru/inwords/inwords/core/error_handler/ErrorDataToDomainMapper.kt
  Android/app/src/main/java/ru/inwords/inwords/core/error_handler/ErrorProcessorImpl.kt
  Android/app/src/main/java/ru/inwords/inwords/core/error_handler/GrpcStatusMapper.kt
  Android/app/src/main/java/ru/inwords/inwords/core/error_handler/NetworkRequestStatus.kt
  Android/app/src/main/java/ru/inwords/inwords/game/data/grpc/WordSetGrpcService.kt
  Android/app/src/main/java/ru/inwords/inwords/game/data/repository/GameRemoteRepository.kt
  Android/app/src/main/java/ru/inwords/inwords/game/di/WordSetsModule.kt
  Android/app/src/main/java/ru/inwords/inwords/game/presentation/game_levels/recycler/GameLevelViewHolder.kt
  Android/app/src/main/java/ru/inwords/inwords/main_activity/data/source/remote/WebRequestsManagerAuthorised.kt
  Android/app/src/main/java/ru/inwords/inwords/main_activity/data/source/remote/WebRequestsManagerAuthorisedImpl.kt
  Android/app/src/main/java/ru/inwords/inwords/main_activity/di/AppComponent.kt
  Android/app/src/main/java/ru/inwords/inwords/main_activity/di/AppModule.kt
  Android/app/src/main/java/ru/inwords/inwords/main_activity/di/DataAbstractModule.kt
  Android/app/src/main/java/ru/inwords/inwords/main_activity/di/DataSourcesModule.kt
  Android/app/src/main/java/ru/inwords/inwords/network/AuthorisedRequestsManager.kt
  Android/app/src/main/java/ru/inwords/inwords/network/SessionHelper.kt
  Android/app/src/main/java/ru/inwords/inwords/network/di/NetworkCoreModule.kt
  Android/app/src/main/java/ru/inwords/inwords/network/grpc/GrpcStatus.kt
  Android/app/src/main/java/ru/inwords/inwords/network/grpc/LoggingClientInterceptor.kt
  Android/app/src/main/java/ru/inwords/inwords/network/grpc/ManagedChannelProvider.kt
  Android/app/src/main/java/ru/inwords/inwords/network/grpc/TokenHeaderAttachingClientInterceptor.kt
  Android/app/src/main/java/ru/inwords/inwords/profile/data/grpc/ProfileGrpcService.kt
  Android/app/src/main/java/ru/inwords/inwords/profile/data/repository/UserRemoteRepository.kt
  Android/app/src/main/java/ru/inwords/inwords/profile/di/ProfileModule.kt
  Android/app/src/main/java/ru/inwords/inwords/texttospeech/data/grpc/TtsGrpcService.kt
  Android/app/src/main/java/ru/inwords/inwords/texttospeech/data/repository/TtsRemoteRepository.kt
  Android/app/src/main/java/ru/inwords/inwords/texttospeech/di/TtsModule.kt
  Android/app/src/main/java/ru/inwords/inwords/translation/data/grpc/DictionaryGrpcService.kt
  Android/app/src/main/java/ru/inwords/inwords/translation/data/repository/TranslationWordsWebApiRepository.kt
  Android/app/src/main/java/ru/inwords/inwords/translation/di/TranslationModule.kt
  Android/app/src/main/res/layout/game_level_info.xml
  Android/build.gradle
  Android/designcorelib/src/main/res/values/strings.xml
Labels: bugfix, dependencies, enhancement

#335 Update Incremental counter
  WebApi/InWords.WebApi/azure-pipelines.yml
Labels: API Release
